"""initial_policy_schema

Revision ID: 0b106c6c7a43
Revises: 
Create Date: 2026-06-29 20:13:56.824049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b106c6c7a43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giggso_baseline_deny',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), server_default=sa.text("'config/unauthorized.csv'"), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_giggso_baseline_deny_giggso_baseline_severity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giggso_baseline_deny'))
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('s3_bucket', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs')),
    sa.UniqueConstraint('slug', name=op.f('uq_orgs_slug'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('pk_schema_migrations'))
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_teams_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_teams_org_slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('is_org_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_users_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('approved_tools',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('domain_pattern', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('overrides_giggso', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("overrides_giggso = false OR (reason IS NOT NULL AND approved_by IS NOT NULL AND scope = 'org')", name=op.f('ck_approved_tools_giggso_override_guarded')),
    sa.CheckConstraint("scope IN ('org','team','user')", name=op.f('ck_approved_tools_approved_scope')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_approved_tools_added_by_users')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_approved_tools_approved_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_approved_tools_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_approved_tools_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approved_tools_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approved_tools'))
    )
    op.create_index('ix_approved_tools_org_scope', 'approved_tools', ['org_id', 'scope'], unique=False)
    op.create_index('ix_approved_tools_team', 'approved_tools', ['team_id'], unique=False)
    op.create_index('ix_approved_tools_user', 'approved_tools', ['user_id'], unique=False)
    op.create_table('blacklisted_tools',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('org','team','user')", name=op.f('ck_blacklisted_tools_blacklisted_scope')),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_blacklisted_tools_blacklisted_severity')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_blacklisted_tools_added_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_blacklisted_tools_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_blacklisted_tools_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blacklisted_tools_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklisted_tools'))
    )
    op.create_index('ix_blacklisted_org', 'blacklisted_tools', ['org_id', 'domain'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_team_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_index('ix_blacklisted_org', table_name='blacklisted_tools')
    op.drop_table('blacklisted_tools')
    op.drop_index('ix_approved_tools_user', table_name='approved_tools')
    op.drop_index('ix_approved_tools_team', table_name='approved_tools')
    op.drop_index('ix_approved_tools_org_scope', table_name='approved_tools')
    op.drop_table('approved_tools')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('schema_migrations')
    op.drop_table('orgs')
    op.drop_table('giggso_baseline_deny')
    # ### end Alembic commands ###
